spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:test
    username: heatmap
    password: heatmap
    driver-class-name: oracle.jdbc.driver.OracleDriver
  type: com.zaxxer.hikari.HikariDataSource
  hikari:
    minimum-idle: 5
    maximum-pool-size: 15
    auto-commit: true
    idle-timeout: 30000
    pool-name: DatebookHikariCP
    max-lifetime: 1800000
    connection-timeout: 30000
  data:
    jpa:
      repositories:
        enabled: true
    rest:
      detection-strategy: annotated
  jpa:
    show-sql: false
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
        type: trace
        dialect: org.hibernate.dialect.Oracle12cDialect
  logging:
    level:
      root: info 
  mvc:
    static-path-pattern: /**
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

server:
  port: 8081
  servlet:
    context-path: /

logging:
  pattern:
    console: "%d %-5level %logger{4} [%X{RSYS_TENANT}-%X{WECHAT_APP_ID}-%X{REQUEST_ID}]: %msg%n"
    file: "%d %-5level %logger{4} [%X{RSYS_TENANT}-%X{WECHAT_APP_ID}-%X{REQUEST_ID}]: %msg%n"
  level:
    root: error
    com.responsys.provider.oardc: debug